name: Build and Release Dictionaries Daily

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Download Latest CSVs
        run: npm run download

      - name: Build Dictionaries
        run: |
          npm run buildTermDict
          npm run buildHonziDict

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create and Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          tag_name: ${{ steps.date.outputs.date }}
          name: ${{ steps.date.outputs.date }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            This is an automated release of the latest Words.hk for Yomitan.
            For more information, please see the [README](https://github.com/MarvNC/wordshk-yomitan).
            Download the latest release below: the file name should look like `Words.hk.YYYY-MM-DD.zip`.
